homeassistant: false
frontend: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://kavanet.io
serial:
  port: /dev/ttyUSB0
advanced:
  network_key:
    - 181
    - 18
    - 121
    - 192
    - 167
    - 211
    - 138
    - 184
    - 73
    - 155
    - 2
    - 41
    - 40
    - 43
    - 165
    - 28
  pan_id: 56898
  ext_pan_id:
    - 59
    - 84
    - 244
    - 59
    - 252
    - 213
    - 15
    - 136
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0xa4c138e65f0b9c66':
    friendly_name: livingRoomPlug
  '0xa4c138161d8fea70':
    friendly_name: livingRoomLamp
  '0xa4c13888b7a39eef':
    friendly_name: trainingRoomPlug
  '0xa4c1383a4d2be600':
    friendly_name: kitchenStrip
  '0x00124b002a657399':
    friendly_name: trainingRoomSensor
  '0x00124b002a5711a2':
    friendly_name: livingRoomButton
  '0xa4c138f82857c541':
    friendly_name: eggChair
  '0x00124b00292f5df6':
    friendly_name: studyButton
  '0x00124b002a65a414':
    friendly_name: printerRoomSensor
  '0x00124b002a6555fa':
    friendly_name: livingRoomSensor
  '0x00124b0029334712':
    friendly_name: trainingRoomMotion
  '0x00124b002a6570b8':
    friendly_name: studySensor
  '0x00124b002a657a8b':
    friendly_name: bedRoomSensor
  '0x00124b002932ef87':
    friendly_name: studyMotion
