homeassistant: false
frontend: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://kavanet.io
serial:
  port: /dev/ttyUSB0
advanced:
  network_key:
    - 181
    - 18
    - 121
    - 192
    - 167
    - 211
    - 138
    - 184
    - 73
    - 155
    - 2
    - 41
    - 40
    - 43
    - 165
    - 28
  pan_id: 56898
  ext_pan_id:
    - 59
    - 84
    - 244
    - 59
    - 252
    - 213
    - 15
    - 136
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0x00124b002a5711a2':
    friendly_name: mySwitch
